import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * `cn` — shadcn-style class merger. The only dependency the skill-produced
 * BoardPanel.tsx imports (`@/lib/utils`). Kept minimal; in a real shadcn
 * project this is generated by `shadcn init`.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
